package bastian.gwt.client;

import com.google.gwt.user.client.ui.CheckBox;
import com.google.gwt.user.client.ui.MultiWordSuggestOracle;
import com.google.gwt.user.client.ui.Panel;
import com.google.gwt.user.client.ui.SuggestBox;
import com.google.gwt.user.client.ui.TabPanel;
import com.google.gwt.user.client.ui.Tree;
import com.google.gwt.user.client.ui.TreeItem;
import com.google.gwt.user.datepicker.client.DatePicker;
import java.util.Date;

public class WidgetSample extends SampleAbstract {

  private static boolean init = false;

  public static TabPanel tp;
  public static Tree t;
  public static MultiWordSuggestOracle mwso;
  public static SuggestBox sb;
  public static DatePicker dp;

  public static void run(Panel root) {
    SampleAbstract.run(root);

    WidgetSample.init();

    root.add(tp);
  }

  public static void init() {
    if (init != true) {
      initTree();
      initSuggestBox();
      initDatePicker();

      tp = new TabPanel();
      tp.add(t, "Simple tree");
      tp.add(sb, "Very simple suggestbox");
      tp.add(dp, "Simple datepicker");
      tp.selectTab(0);

      init = true;
    }
  }

  private static void initDatePicker() {
    dp = new DatePicker();
    dp.setValue(new Date(), true);
  }

  private static void initTree() {
    TreeItem root = new TreeItem("Parent");
    root.addItem("Child 1");
    root.addItem("Child 2");

    TreeItem child = new TreeItem("Child 3");
    child.addItem("Child 1");
    child.addItem(new CheckBox("Yes or No?"));

    root.addItem(child);

    t = new Tree();
    t.addItem(root);
  }

  private static void initSuggestBox() {
    mwso = new MultiWordSuggestOracle();
    mwso.add("Aberdeen");
    mwso.add("Ada");
    mwso.add("Adamsville");
    mwso.add("Addyston");
    mwso.add("Adelphi");
    mwso.add("Adena");
    mwso.add("Adrian");
    mwso.add("Akron");
    mwso.add("Albany");
    mwso.add("Alexandria");
    mwso.add("Alger");
    mwso.add("Alledonia");
    mwso.add("Alliance");
    mwso.add("Alpha");
    mwso.add("Alvada");
    mwso.add("Alvordton");
    mwso.add("Amanda");
    mwso.add("Amelia");
    mwso.add("Amesville");
    mwso.add("Amherst");
    mwso.add("Amlin");
    mwso.add("Amsden");
    mwso.add("Amsterdam");
    mwso.add("Andover");
    mwso.add("Anna");
    mwso.add("Ansonia");
    mwso.add("Antwerp");
    mwso.add("Apple Creek");
    mwso.add("Arcadia");
    mwso.add("Arcanum");
    mwso.add("Archbold");
    mwso.add("Arlington");
    mwso.add("Ashland");
    mwso.add("Ashley");
    mwso.add("Ashtabula");
    mwso.add("Ashville");
    mwso.add("Athens");
    mwso.add("Attica");
    mwso.add("Atwater");
    mwso.add("Augusta");
    mwso.add("Aurora");
    mwso.add("Austinburg");
    mwso.add("Ava");
    mwso.add("Avon");
    mwso.add("Avon Lake");
    mwso.add("Bainbridge");
    mwso.add("Bakersville");
    mwso.add("Baltic");
    mwso.add("Baltimore");
    mwso.add("Bannock");
    mwso.add("Barberton");
    mwso.add("Barlow");
    mwso.add("Barnesville");
    mwso.add("Bartlett");
    mwso.add("Barton");
    mwso.add("Bascom");
    mwso.add("Batavia");
    mwso.add("Bath");
    mwso.add("Bay Village");
    mwso.add("Beach City");
    mwso.add("Beachwood");
    mwso.add("Beallsville");
    mwso.add("Beaver");
    mwso.add("Beaverdam");
    mwso.add("Bedford");
    mwso.add("Bellaire");
    mwso.add("Bellbrook");
    mwso.add("Belle Center");
    mwso.add("Belle Valley");
    mwso.add("Bellefontaine");
    mwso.add("Bellevue");
    mwso.add("Bellville");
    mwso.add("Belmont");
    mwso.add("Belmore");
    mwso.add("Beloit");
    mwso.add("Belpre");
    mwso.add("Benton Ridge");
    mwso.add("Bentonville");
    mwso.add("Berea");
    mwso.add("Bergholz");
    mwso.add("Berkey");
    mwso.add("Berlin");
    mwso.add("Berlin Center");
    mwso.add("Berlin Heights");
    mwso.add("Bethel");
    mwso.add("Bethesda");
    mwso.add("Bettsville");
    mwso.add("Beverly");
    mwso.add("Bidwell");
    mwso.add("Big Prairie");
    mwso.add("Birmingham");
    mwso.add("Blacklick");
    mwso.add("Bladensburg");
    mwso.add("Blaine");
    mwso.add("Blakeslee");
    mwso.add("Blanchester");
    mwso.add("Blissfield");
    mwso.add("Bloomdale");
    mwso.add("Bloomingburg");
    mwso.add("Bloomingdale");
    mwso.add("Bloomville");
    mwso.add("Blue Creek");
    mwso.add("Blue Rock");
    mwso.add("Bluffton");
    mwso.add("Bolivar");
    mwso.add("Botkins");
    mwso.add("Bourneville");
    mwso.add("Bowerston");
    mwso.add("Bowersville");
    mwso.add("Bowling Green");
    mwso.add("Bradford");
    mwso.add("Bradner");
    mwso.add("Brady Lake");
    mwso.add("Brecksville");
    mwso.add("Bremen");
    mwso.add("Brewster");
    mwso.add("Brice");
    mwso.add("Bridgeport");
    mwso.add("Brilliant");
    mwso.add("Brinkhaven");
    mwso.add("Bristolville");
    mwso.add("Broadview Heights");
    mwso.add("Broadway");
    mwso.add("Brookfield");
    mwso.add("Brookpark");
    mwso.add("Brookville");
    mwso.add("Brownsville");
    mwso.add("Brunswick");
    mwso.add("Bryan");
    mwso.add("Buchtel");
    mwso.add("Buckeye Lake");
    mwso.add("Buckland");
    mwso.add("Bucyrus");
    mwso.add("Buffalo");
    mwso.add("Buford");
    mwso.add("Burbank");
    mwso.add("Burghill");
    mwso.add("Burgoon");
    mwso.add("Burkettsville");
    mwso.add("Burton");
    mwso.add("Butler");
    mwso.add("Byesville");
    mwso.add("Cable");
    mwso.add("Cadiz");
    mwso.add("Cairo");
    mwso.add("Caldwell");
    mwso.add("Caledonia");
    mwso.add("Cambridge");
    mwso.add("Camden");
    mwso.add("Cameron");
    mwso.add("Camp Dennison");
    mwso.add("Campbell");
    mwso.add("Canal Fulton");
    mwso.add("Canal Winchester");
    mwso.add("Canfield");
    mwso.add("Canton");
    mwso.add("Carbon Hill");
    mwso.add("Carbondale");
    mwso.add("Cardington");
    mwso.add("Carey");
    mwso.add("Carroll");
    mwso.add("Carrollton");
    mwso.add("Casstown");
    mwso.add("Castalia");
    mwso.add("Catawba");
    mwso.add("Cecil");
    mwso.add("Cedarville");
    mwso.add("Celina");
    mwso.add("Centerburg");
    mwso.add("Chagrin Falls");
    mwso.add("Chandlersville");
    mwso.add("Chardon");
    mwso.add("Charm");
    mwso.add("Chatfield");
    mwso.add("Chauncey");
    mwso.add("Cherry Fork");
    mwso.add("Chesapeake");
    mwso.add("Cheshire");
    mwso.add("Chester");
    mwso.add("Chesterhill");
    mwso.add("Chesterland");
    mwso.add("Chesterville");
    mwso.add("Chickasaw");
    mwso.add("Chillicothe");
    mwso.add("Chilo");
    mwso.add("Chippewa Lake");
    mwso.add("Christiansburg");
    mwso.add("Cincinnati");
    mwso.add("Circleville");
    mwso.add("Clarington");
    mwso.add("Clarksburg");
    mwso.add("Clarksville");
    mwso.add("Clay Center");
    mwso.add("Clayton");
    mwso.add("Cleveland");
    mwso.add("Cleves");
    mwso.add("Clifton");
    mwso.add("Clinton");
    mwso.add("Cloverdale");
    mwso.add("Clyde");
    mwso.add("Coal Run");
    mwso.add("Coalton");
    mwso.add("Coldwater");
    mwso.add("Colerain");
    mwso.add("College Corner");
    mwso.add("Collins");
    mwso.add("Collinsville");
    mwso.add("Colton");
    mwso.add("Columbia Station");
    mwso.add("Columbiana");
    mwso.add("Columbus");
    mwso.add("Columbus Grove");
    mwso.add("Commercial Point");
    mwso.add("Conesville");
    mwso.add("Conneaut");
    mwso.add("Conover");
    mwso.add("Continental");
    mwso.add("Convoy");
    mwso.add("Coolville");
    mwso.add("Corning");
    mwso.add("Cortland");
    mwso.add("Coshocton");
    mwso.add("Covington");
    mwso.add("Creola");
    mwso.add("Crestline");
    mwso.add("Creston");
    mwso.add("Crooksville");
    mwso.add("Croton");
    mwso.add("Crown City");
    mwso.add("Cuba");
    mwso.add("Cumberland");
    mwso.add("Curtice");
    mwso.add("Custar");
    mwso.add("Cutler");
    mwso.add("Cuyahoga Falls");
    mwso.add("Cygnet");
    mwso.add("Cynthiana");
    mwso.add("Dalton");
    mwso.add("Damascus");
    mwso.add("Danville");
    mwso.add("Dayton");
    mwso.add("De Graff");
    mwso.add("Decatur");
    mwso.add("Deerfield");
    mwso.add("Deersville");
    mwso.add("Defiance");
    mwso.add("Delaware");
    mwso.add("Dellroy");
    mwso.add("Delphos");
    mwso.add("Delta");
    mwso.add("Dennison");
    mwso.add("Derby");
    mwso.add("Derwent");
    mwso.add("Deshler");
    mwso.add("Dexter City");
    mwso.add("Diamond");
    mwso.add("Dillonvale");
    mwso.add("Dola");
    mwso.add("Donnelsville");
    mwso.add("Dorset");
    mwso.add("Dover");
    mwso.add("Doylestown");
    mwso.add("Dresden");
    mwso.add("Dublin");
    mwso.add("Dunbridge");
    mwso.add("Duncan Falls");
    mwso.add("Dundee");
    mwso.add("Dunkirk");
    mwso.add("Dupont");
    mwso.add("East Claridon");
    mwso.add("East Fultonham");
    mwso.add("East Liberty");
    mwso.add("East Liverpool");
    mwso.add("East Palestine");
    mwso.add("East Rochester");
    mwso.add("East Sparta");
    mwso.add("East Springfield");
    mwso.add("Eastlake");
    mwso.add("Eaton");
    mwso.add("Edgerton");
    mwso.add("Edison");
    mwso.add("Edon");
    mwso.add("Eldorado");
    mwso.add("Elgin");
    mwso.add("Elkton");
    mwso.add("Ellsworth");
    mwso.add("Elmore");
    mwso.add("Elyria");
    mwso.add("Empire");
    mwso.add("Englewood");
    mwso.add("Enon");
    mwso.add("Etna");
    mwso.add("Euclid");
    mwso.add("Evansport");
    mwso.add("Fairborn");
    mwso.add("Fairfield");
    mwso.add("Fairpoint");
    mwso.add("Fairview");
    mwso.add("Farmdale");
    mwso.add("Farmer");
    mwso.add("Farmersville");
    mwso.add("Fayette");
    mwso.add("Fayetteville");
    mwso.add("Feesburg");
    mwso.add("Felicity");
    mwso.add("Findlay");
    mwso.add("Flat Rock");
    mwso.add("Fleming");
    mwso.add("Fletcher");
    mwso.add("Flushing");
    mwso.add("Forest");
    mwso.add("Fort Jennings");
    mwso.add("Fort Loramie");
    mwso.add("Fort Recovery");
    mwso.add("Fostoria");
    mwso.add("Fowler");
    mwso.add("Frankfort");
    mwso.add("Franklin");
    mwso.add("Franklin Furnace");
    mwso.add("Frazeysburg");
    mwso.add("Fredericksburg");
    mwso.add("Fredericktown");
    mwso.add("Freeport");
    mwso.add("Fremont");
    mwso.add("Fresno");
    mwso.add("Friendship");
    mwso.add("Fulton");
    mwso.add("Fultonham");
    mwso.add("Galena");
    mwso.add("Galion");
    mwso.add("Gallipolis");
    mwso.add("Galloway");
    mwso.add("Gambier");
    mwso.add("Garrettsville");
    mwso.add("Gates Mills");
    mwso.add("Geneva");
    mwso.add("Genoa");
    mwso.add("Georgetown");
    mwso.add("Germantown");
    mwso.add("Gettysburg");
    mwso.add("Gibsonburg");
    mwso.add("Girard");
    mwso.add("Glandorf");
    mwso.add("Glencoe");
    mwso.add("Glenford");
    mwso.add("Glenmont");
    mwso.add("Glouster");
    mwso.add("Gnadenhutten");
    mwso.add("Gomer");
    mwso.add("Goshen");
    mwso.add("Grafton");
    mwso.add("Grand Rapids");
    mwso.add("Grand River");
    mwso.add("Granville");
    mwso.add("Gratiot");
    mwso.add("Gratis");
    mwso.add("Graysville");
    mwso.add("Graytown");
    mwso.add("Green");
    mwso.add("Green Camp");
    mwso.add("Green Springs");
    mwso.add("Greenfield");
    mwso.add("Greenford");
    mwso.add("Greentown");
    mwso.add("Greenville");
    mwso.add("Greenwich");
    mwso.add("Grelton");
    mwso.add("Grove City");
    mwso.add("Groveport");
    mwso.add("Grover Hill");
    mwso.add("Guysville");
    mwso.add("Gypsum");
    mwso.add("Hallsville");
    mwso.add("Hamden");
    mwso.add("Hamersville");
    mwso.add("Hamilton");
    mwso.add("Hamler");
    mwso.add("Hammondsville");
    mwso.add("Hannibal");
    mwso.add("Hanoverton");
    mwso.add("Harbor View");
    mwso.add("Harlem Springs");
    mwso.add("Harpster");
    mwso.add("Harrisburg");
    mwso.add("Harrison");
    mwso.add("Harrisville");
    mwso.add("Harrod");
    mwso.add("Hartford");
    mwso.add("Hartville");
    mwso.add("Harveysburg");
    mwso.add("Haskins");
    mwso.add("Haverhill");
    mwso.add("Haviland");
    mwso.add("Haydenville");
    mwso.add("Hayesville");
    mwso.add("Heath");
    mwso.add("Hebron");
    mwso.add("Helena");
    mwso.add("Hicksville");
    mwso.add("Higginsport");
    mwso.add("Highland");
    mwso.add("Hilliard");
    mwso.add("Hillsboro");
    mwso.add("Hinckley");
    mwso.add("Hiram");
    mwso.add("Hockingport");
    mwso.add("Holgate");
    mwso.add("Holland");
    mwso.add("Hollansburg");
    mwso.add("Holloway");
    mwso.add("Holmesville");
    mwso.add("Homer");
    mwso.add("Homerville");
    mwso.add("Homeworth");
    mwso.add("Hooven");
    mwso.add("Hopedale");
    mwso.add("Hopewell");
    mwso.add("Houston");
    mwso.add("Howard");
    mwso.add("Hoytville");
    mwso.add("Hubbard");
    mwso.add("Hudson");
    mwso.add("Huntsburg");
    mwso.add("Huntsville");
    mwso.add("Huron");
    mwso.add("Iberia");
    mwso.add("Independence");
    mwso.add("Irondale");
    mwso.add("Ironton");
    mwso.add("Irwin");
    mwso.add("Isle Saint George");
    mwso.add("Jackson");
    mwso.add("Jackson Center");
    mwso.add("Jacksontown");
    mwso.add("Jacksonville");
    mwso.add("Jacobsburg");
    mwso.add("Jamestown");
    mwso.add("Jasper");
    mwso.add("Jefferson");
    mwso.add("Jeffersonville");
    mwso.add("Jenera");
    mwso.add("Jeromesville");
    mwso.add("Jerry City");
    mwso.add("Jerusalem");
    mwso.add("Jewell");
    mwso.add("Jewett");
    mwso.add("Johnstown");
    mwso.add("Junction City");
    mwso.add("Kalida");
    mwso.add("Kansas");
    mwso.add("Keene");
    mwso.add("Kelleys Island");
    mwso.add("Kensington");
    mwso.add("Kent");
    mwso.add("Kenton");
    mwso.add("Kerr");
    mwso.add("Kettlersville");
    mwso.add("Kidron");
    mwso.add("Kilbourne");
    mwso.add("Killbuck");
    mwso.add("Kimbolton");
    mwso.add("Kings Mills");
    mwso.add("Kingston");
    mwso.add("Kingsville");
    mwso.add("Kinsman");
    mwso.add("Kipling");
    mwso.add("Kipton");
    mwso.add("Kirby");
    mwso.add("Kirkersville");
    mwso.add("Kitts Hill");
    mwso.add("Kunkle");
    mwso.add("La Rue");
    mwso.add("Lacarne");
    mwso.add("Lafayette");
    mwso.add("Lafferty");
    mwso.add("Lagrange");
    mwso.add("Laings");
    mwso.add("Lake Milton");
    mwso.add("Lakemore");
    mwso.add("Lakeside Marblehead");
    mwso.add("Lakeview");
    mwso.add("Lakeville");
    mwso.add("Lakewood");
    mwso.add("Lancaster");
    mwso.add("Langsville");
    mwso.add("Lansing");
    mwso.add("Latham");
    mwso.add("Latty");
    mwso.add("Laura");
    mwso.add("Laurelville");
    mwso.add("Leavittsburg");
    mwso.add("Lebanon");
    mwso.add("Lees Creek");
    mwso.add("Leesburg");
    mwso.add("Leesville");
    mwso.add("Leetonia");
    mwso.add("Leipsic");
    mwso.add("Lemoyne");
    mwso.add("Lewis Center");
    mwso.add("Lewisburg");
    mwso.add("Lewistown");
    mwso.add("Lewisville");
    mwso.add("Liberty Center");
    mwso.add("Lima");
    mwso.add("Limaville");
    mwso.add("Lindsey");
    mwso.add("Lisbon");
    mwso.add("Litchfield");
    mwso.add("Lithopolis");
    mwso.add("Little Hocking");
    mwso.add("Lockbourne");
    mwso.add("Lodi");
    mwso.add("Logan");
    mwso.add("London");
    mwso.add("Londonderry");
    mwso.add("Long Bottom");
    mwso.add("Lorain");
    mwso.add("Lore City");
    mwso.add("Loudonville");
    mwso.add("Louisville");
    mwso.add("Loveland");
    mwso.add("Lowell");
    mwso.add("Lowellville");
    mwso.add("Lower Salem");
    mwso.add("Lucas");
    mwso.add("Lucasville");
    mwso.add("Luckey");
    mwso.add("Ludlow Falls");
    mwso.add("Lynchburg");
    mwso.add("Lynx");
    mwso.add("Lyons");
    mwso.add("Macedonia");
    mwso.add("Macksburg");
    mwso.add("Madison");
    mwso.add("Magnetic Springs");
    mwso.add("Magnolia");
    mwso.add("Maineville");
    mwso.add("Malaga");
    mwso.add("Malinta");
    mwso.add("Malta");
    mwso.add("Malvern");
    mwso.add("Manchester");
    mwso.add("Mansfield");
    mwso.add("Mantua");
    mwso.add("Maple Heights");
    mwso.add("Maplewood");
    mwso.add("Marathon");
    mwso.add("Marengo");
    mwso.add("Maria Stein");
    mwso.add("Marietta");
    mwso.add("Marion");
    mwso.add("Mark Center");
    mwso.add("Marshallville");
    mwso.add("Martel");
    mwso.add("Martin");
    mwso.add("Martins Ferry");
    mwso.add("Martinsburg");
    mwso.add("Martinsville");
    mwso.add("Marysville");
    mwso.add("Mason");
    mwso.add("Massillon");
    mwso.add("Masury");
    mwso.add("Maumee");
    mwso.add("Maximo");
    mwso.add("Maynard");
    mwso.add("Mc Arthur");
    mwso.add("Mc Clure");
    mwso.add("Mc Comb");
    mwso.add("Mc Connelsville");
    mwso.add("Mc Cutchenville");
    mwso.add("Mc Dermott");
    mwso.add("Mc Donald");
    mwso.add("Mc Guffey");
    mwso.add("Mechanicsburg");
    mwso.add("Mechanicstown");
    mwso.add("Medina");
    mwso.add("Medway");
    mwso.add("Melmore");
    mwso.add("Melrose");
    mwso.add("Mendon");
    mwso.add("Mentor");
    mwso.add("Mesopotamia");
    mwso.add("Metamora");
    mwso.add("Miamisburg");
    mwso.add("Miamitown");
    mwso.add("Miamiville");
    mwso.add("Middle Bass");
    mwso.add("Middle Point");
    mwso.add("Middlebranch");
    mwso.add("Middleburg");
    mwso.add("Middlefield");
    mwso.add("Middleport");
    mwso.add("Middletown");
    mwso.add("Midland");
    mwso.add("Midvale");
    mwso.add("Milan");
    mwso.add("Milford");
    mwso.add("Milford Center");
    mwso.add("Millbury");
    mwso.add("Milledgeville");
    mwso.add("Miller City");
    mwso.add("Millersburg");
    mwso.add("Millersport");
    mwso.add("Millfield");
    mwso.add("Milton Center");
    mwso.add("Mineral City");
    mwso.add("Mineral Ridge");
    mwso.add("Minerva");
    mwso.add("Minford");
    mwso.add("Mingo");
    mwso.add("Mingo Junction");
    mwso.add("Minster");
    mwso.add("Mogadore");
    mwso.add("Monclova");
    mwso.add("Monroe");
    mwso.add("Monroeville");
    mwso.add("Montezuma");
    mwso.add("Montpelier");
    mwso.add("Montville");
    mwso.add("Morral");
    mwso.add("Morristown");
    mwso.add("Morrow");
    mwso.add("Moscow");
    mwso.add("Mount Blanchard");
    mwso.add("Mount Cory");
    mwso.add("Mount Eaton");
    mwso.add("Mount Gilead");
    mwso.add("Mount Hope");
    mwso.add("Mount Liberty");
    mwso.add("Mount Orab");
    mwso.add("Mount Perry");
    mwso.add("Mount Pleasant");
    mwso.add("Mount Saint Joseph");
    mwso.add("Mount Sterling");
    mwso.add("Mount Vernon");
    mwso.add("Mount Victory");
    mwso.add("Mowrystown");
    mwso.add("Moxahala");
    mwso.add("Munroe Falls");
    mwso.add("Murray City");
    mwso.add("Nankin");
    mwso.add("Napoleon");
    mwso.add("Nashport");
    mwso.add("Nashville");
    mwso.add("Navarre");
    mwso.add("Neapolis");
    mwso.add("Neffs");
    mwso.add("Negley");
    mwso.add("Nelsonville");
    mwso.add("Nevada");
    mwso.add("Neville");
    mwso.add("New Albany");
    mwso.add("New Athens");
    mwso.add("New Bavaria");
    mwso.add("New Bloomington");
    mwso.add("New Bremen");
    mwso.add("New Carlisle");
    mwso.add("New Concord");
    mwso.add("New Hampshire");
    mwso.add("New Haven");
    mwso.add("New Holland");
    mwso.add("New Knoxville");
    mwso.add("New Lebanon");
    mwso.add("New Lexington");
    mwso.add("New London");
    mwso.add("New Madison");
    mwso.add("New Marshfield");
    mwso.add("New Matamoras");
    mwso.add("New Middletown");
    mwso.add("New Paris");
    mwso.add("New Philadelphia");
    mwso.add("New Plymouth");
    mwso.add("New Richmond");
    mwso.add("New Riegel");
    mwso.add("New Rumley");
    mwso.add("New Springfield");
    mwso.add("New Straitsville");
    mwso.add("New Vienna");
    mwso.add("New Washington");
    mwso.add("New Waterford");
    mwso.add("New Weston");
    mwso.add("Newark");
    mwso.add("Newbury");
    mwso.add("Newcomerstown");
    mwso.add("Newport");
    mwso.add("Newton Falls");
    mwso.add("Newtonsville");
    mwso.add("Ney");
    mwso.add("Niles");
    mwso.add("North Baltimore");
    mwso.add("North Bend");
    mwso.add("North Benton");
    mwso.add("North Bloomfield");
    mwso.add("North Fairfield");
    mwso.add("North Georgetown");
    mwso.add("North Hampton");
    mwso.add("North Jackson");
    mwso.add("North Kingsville");
    mwso.add("North Lawrence");
    mwso.add("North Lewisburg");
    mwso.add("North Lima");
    mwso.add("North Olmsted");
    mwso.add("North Ridgeville");
    mwso.add("North Robinson");
    mwso.add("North Royalton");
    mwso.add("North Star");
    mwso.add("Northfield");
    mwso.add("Northwood");
    mwso.add("Norwalk");
    mwso.add("Norwich");
    mwso.add("Nova");
    mwso.add("Novelty");
    mwso.add("Oak Harbor");
    mwso.add("Oak Hill");
    mwso.add("Oakwood");
    mwso.add("Oberlin");
    mwso.add("Oceola");
    mwso.add("Ohio City");
    mwso.add("Okeana");
    mwso.add("Okolona");
    mwso.add("Old Fort");
    mwso.add("Old Washington");
    mwso.add("Olmsted Falls");
    mwso.add("Ontario");
    mwso.add("Orangeville");
    mwso.add("Oregon");
    mwso.add("Oregonia");
    mwso.add("Orient");
    mwso.add("Orrville");
    mwso.add("Orwell");
    mwso.add("Osgood");
    mwso.add("Ostrander");
    mwso.add("Ottawa");
    mwso.add("Ottoville");
    mwso.add("Otway");
    mwso.add("Overpeck");
    mwso.add("Owensville");
    mwso.add("Oxford");
    mwso.add("Painesville");
    mwso.add("Palestine");
    mwso.add("Pandora");
    mwso.add("Paris");
    mwso.add("Parkman");
    mwso.add("Pataskala");
    mwso.add("Patriot");
    mwso.add("Paulding");
    mwso.add("Payne");
    mwso.add("Pedro");
    mwso.add("Peebles");
    mwso.add("Pemberton");
    mwso.add("Pemberville");
    mwso.add("Peninsula");
    mwso.add("Perry");
    mwso.add("Perrysburg");
    mwso.add("Perrysville");
    mwso.add("Petersburg");
    mwso.add("Pettisville");
    mwso.add("Phillipsburg");
    mwso.add("Philo");
    mwso.add("Pickerington");
    mwso.add("Piedmont");
    mwso.add("Pierpont");
    mwso.add("Piketon");
    mwso.add("Piney Fork");
    mwso.add("Pioneer");
    mwso.add("Piqua");
    mwso.add("Pitsburg");
    mwso.add("Plain City");
    mwso.add("Plainfield");
    mwso.add("Pleasant City");
    mwso.add("Pleasant Hill");
    mwso.add("Pleasant Plain");
    mwso.add("Pleasantville");
    mwso.add("Plymouth");
    mwso.add("Polk");
    mwso.add("Pomeroy");
    mwso.add("Port Clinton");
    mwso.add("Port Jefferson");
    mwso.add("Port Washington");
    mwso.add("Port William");
    mwso.add("Portage");
    mwso.add("Portland");
    mwso.add("Portsmouth");
    mwso.add("Potsdam");
    mwso.add("Powell");
    mwso.add("Powhatan Point");
    mwso.add("Proctorville");
    mwso.add("Prospect");
    mwso.add("Put in Bay");
    mwso.add("Quaker City");
    mwso.add("Quincy");
    mwso.add("Racine");
    mwso.add("Radnor");
    mwso.add("Randolph");
    mwso.add("Rarden");
    mwso.add("Ravenna");
    mwso.add("Rawson");
    mwso.add("Ray");
    mwso.add("Rayland");
    mwso.add("Raymond");
    mwso.add("Reedsville");
    mwso.add("Reesville");
    mwso.add("Reno");
    mwso.add("Republic");
    mwso.add("Reynoldsburg");
    mwso.add("Richfield");
    mwso.add("Richmond");
    mwso.add("Richmond Dale");
    mwso.add("Richwood");
    mwso.add("Ridgeville Corners");
    mwso.add("Ridgeway");
    mwso.add("Rio Grande");
    mwso.add("Ripley");
    mwso.add("Risingsun");
    mwso.add("Rittman");
    mwso.add("Robertsville");
    mwso.add("Rock Camp");
    mwso.add("Rock Creek");
    mwso.add("Rockbridge");
    mwso.add("Rockford");
    mwso.add("Rocky Ridge");
    mwso.add("Rocky River");
    mwso.add("Rogers");
    mwso.add("Rome");
    mwso.add("Rootstown");
    mwso.add("Roseville");
    mwso.add("Rosewood");
    mwso.add("Ross");
    mwso.add("Rossburg");
    mwso.add("Rossford");
    mwso.add("Roundhead");
    mwso.add("Rudolph");
    mwso.add("Rushsylvania");
    mwso.add("Rushville");
    mwso.add("Russells Point");
    mwso.add("Russellville");
    mwso.add("Russia");
    mwso.add("Rutland");
    mwso.add("Sabina");
    mwso.add("Saint Clairsville");
    mwso.add("Saint Henry");
    mwso.add("Saint Johns");
    mwso.add("Saint Louisville");
    mwso.add("Saint Marys");
    mwso.add("Saint Paris");
    mwso.add("Salem");
    mwso.add("Salesville");
    mwso.add("Salineville");
    mwso.add("Sandusky");
    mwso.add("Sandyville");
    mwso.add("Sarahsville");
    mwso.add("Sardinia");
    mwso.add("Sardis");
    mwso.add("Savannah");
    mwso.add("Scio");
    mwso.add("Scioto Furnace");
    mwso.add("Scott");
    mwso.add("Scottown");
    mwso.add("Seaman");
    mwso.add("Sebring");
    mwso.add("Sedalia");
    mwso.add("Senecaville");
    mwso.add("Seven Mile");
    mwso.add("Seville");
    mwso.add("Shade");
    mwso.add("Shadyside");
    mwso.add("Shandon");
    mwso.add("Sharon Center");
    mwso.add("Sharpsburg");
    mwso.add("Shauck");
    mwso.add("Shawnee");
    mwso.add("Sheffield Lake");
    mwso.add("Shelby");
    mwso.add("Sherrodsville");
    mwso.add("Sherwood");
    mwso.add("Shiloh");
    mwso.add("Short Creek");
    mwso.add("Shreve");
    mwso.add("Sidney");
    mwso.add("Sinking Spring");
    mwso.add("Smithfield");
    mwso.add("Smithville");
    mwso.add("Solon");
    mwso.add("Somerdale");
    mwso.add("Somerset");
    mwso.add("Somerville");
    mwso.add("South Bloomingville");
    mwso.add("South Charleston");
    mwso.add("South Lebanon");
    mwso.add("South Point");
    mwso.add("South Salem");
    mwso.add("South Solon");
    mwso.add("South Vienna");
    mwso.add("South Webster");
    mwso.add("Southington");
    mwso.add("Sparta");
    mwso.add("Spencer");
    mwso.add("Spencerville");
    mwso.add("Spring Valley");
    mwso.add("Springboro");
    mwso.add("Springfield");
    mwso.add("Stafford");
    mwso.add("Sterling");
    mwso.add("Steubenville");
    mwso.add("Stewart");
    mwso.add("Stillwater");
    mwso.add("Stockdale");
    mwso.add("Stockport");
    mwso.add("Stone Creek");
    mwso.add("Stony Ridge");
    mwso.add("Stout");
    mwso.add("Stoutsville");
    mwso.add("Stow");
    mwso.add("Strasburg");
    mwso.add("Stratton");
    mwso.add("Streetsboro");
    mwso.add("Strongsville");
    mwso.add("Struthers");
    mwso.add("Stryker");
    mwso.add("Sugar Grove");
    mwso.add("Sugarcreek");
    mwso.add("Sullivan");
    mwso.add("Sulphur Springs");
    mwso.add("Summerfield");
    mwso.add("Summit Station");
    mwso.add("Summitville");
    mwso.add("Sunbury");
    mwso.add("Swanton");
    mwso.add("Sycamore");
    mwso.add("Sycamore Valley");
    mwso.add("Sylvania");
    mwso.add("Syracuse");
    mwso.add("Tallmadge");
    mwso.add("Tarlton");
    mwso.add("Terrace Park");
    mwso.add("The Plains");
    mwso.add("Thompson");
    mwso.add("Thornville");
    mwso.add("Thurman");
    mwso.add("Thurston");
    mwso.add("Tiffin");
    mwso.add("Tiltonsville");
    mwso.add("Tipp City");
    mwso.add("Tippecanoe");
    mwso.add("Tiro");
    mwso.add("Toledo");
    mwso.add("Tontogany");
    mwso.add("Torch");
    mwso.add("Toronto");
    mwso.add("Tremont City");
    mwso.add("Trenton");
    mwso.add("Trimble");
    mwso.add("Trinway");
    mwso.add("Troy");
    mwso.add("Tuppers Plains");
    mwso.add("Tuscarawas");
    mwso.add("Twinsburg");
    mwso.add("Uhrichsville");
    mwso.add("Union City");
    mwso.add("Union Furnace");
    mwso.add("Unionport");
    mwso.add("Uniontown");
    mwso.add("Unionville");
    mwso.add("Unionville Center");
    mwso.add("Uniopolis");
    mwso.add("Upper Sandusky");
    mwso.add("Urbana");
    mwso.add("Utica");
    mwso.add("Valley City");
    mwso.add("Van Buren");
    mwso.add("Van Wert");
    mwso.add("Vandalia");
    mwso.add("Vanlue");
    mwso.add("Vaughnsville");
    mwso.add("Venedocia");
    mwso.add("Vermilion");
    mwso.add("Verona");
    mwso.add("Versailles");
    mwso.add("Vickery");
    mwso.add("Vienna");
    mwso.add("Vincent");
    mwso.add("Vinton");
    mwso.add("Wadsworth");
    mwso.add("Wakefield");
    mwso.add("Wakeman");
    mwso.add("Walbridge");
    mwso.add("Waldo");
    mwso.add("Walhonding");
    mwso.add("Walnut Creek");
    mwso.add("Wapakoneta");
    mwso.add("Warnock");
    mwso.add("Warren");
    mwso.add("Warsaw");
    mwso.add("Washington Court House");
    mwso.add("Washingtonville");
    mwso.add("Waterford");
    mwso.add("Waterloo");
    mwso.add("Watertown");
    mwso.add("Waterville");
    mwso.add("Wauseon");
    mwso.add("Waverly");
    mwso.add("Wayland");
    mwso.add("Wayne");
    mwso.add("Waynesburg");
    mwso.add("Waynesfield");
    mwso.add("Waynesville");
    mwso.add("Wellington");
    mwso.add("Wellston");
    mwso.add("Wellsville");
    mwso.add("West Alexandria");
    mwso.add("West Chester");
    mwso.add("West Elkton");
    mwso.add("West Farmington");
    mwso.add("West Jefferson");
    mwso.add("West Lafayette");
    mwso.add("West Liberty");
    mwso.add("West Manchester");
    mwso.add("West Mansfield");
    mwso.add("West Millgrove");
    mwso.add("West Milton");
    mwso.add("West Point");
    mwso.add("West Portsmouth");
    mwso.add("West Rushville");
    mwso.add("West Salem");
    mwso.add("West Union");
    mwso.add("West Unity");
    mwso.add("Westerville");
    mwso.add("Westfield Center");
    mwso.add("Westlake");
    mwso.add("Weston");
    mwso.add("Westville");
    mwso.add("Wharton");
    mwso.add("Wheelersburg");
    mwso.add("Whipple");
    mwso.add("White Cottage");
    mwso.add("Whitehouse");
    mwso.add("Wickliffe");
    mwso.add("Wilberforce");
    mwso.add("Wilkesville");
    mwso.add("Willard");
    mwso.add("Williamsburg");
    mwso.add("Williamsfield");
    mwso.add("Williamsport");
    mwso.add("Williamstown");
    mwso.add("Williston");
    mwso.add("Willoughby");
    mwso.add("Willow Wood");
    mwso.add("Willshire");
    mwso.add("Wilmington");
    mwso.add("Wilmot");
    mwso.add("Winchester");
    mwso.add("Windham");
    mwso.add("Windsor");
    mwso.add("Winesburg");
    mwso.add("Wingett Run");
    mwso.add("Winona");
    mwso.add("Wolf Run");
    mwso.add("Woodsfield");
    mwso.add("Woodstock");
    mwso.add("Woodville");
    mwso.add("Wooster");
    mwso.add("Wren");
    mwso.add("Xenia");
    mwso.add("Yellow Springs");
    mwso.add("Yorkshire");
    mwso.add("Yorkville");
    mwso.add("Youngstown");
    mwso.add("Zaleski");
    mwso.add("Zanesfield");
    mwso.add("Zanesville");
    mwso.add("Zoar");

    sb = new SuggestBox(mwso);
    sb.setLimit(10);
  }

}
