function clan(){var Q='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',db='"><\/script>',fb='#',Fb='&',lc='.cache.html',hb='/',Wb='0A4636A467B6BEFF341E98B9F2EDAA1E',Xb='10F9C31695A7114E9D6DBE6F14C7C8BF',Zb='23BA9DCD6C11E31E3FD9C838A77A0DA7',$b='2B36A696BEFB587709AB77C7D0A321A8',_b='2D7BD4B7A64BB1E408B23C6851A211E8',ac='5A5440A5D2C44AD8F648F7861DC54BD1',bc='6BE7B543702ABE9B6B03BBBDF794421D',cc='6EDB51280552C9F957E76591C03A4DFF',dc='7FC56757DF8226EF34C58C068603842F',ec='890BCB809F370887FA1A4B73CF7EE5DC',fc='99644F4B6EF9AA9A9212E01A37C716BC',kc=':',ob='::',nc='<script defer="defer">clan.onInjectionDone(\'clan\')<\/script>',cb='<script id="',rb='=',gb='?',gc='BF41DC0B74D302BF8153DE76CF31046E',tb='Bad handler "',hc='C729CC0E8BFAB31E01499CF8AFCE2604',ic='C92ACF57B810FF32D4F7301A9A31E1D1',jc='DCA157F4CC9CA9375586FAEE86EBCF4E',mc='DOMContentLoaded',eb='SCRIPT',Ib='Unexpected exception in locale detection, using default: ',Hb='_',Gb='__gwt_Locale',bb='__gwt_marker_clan',ib='base',$='baseUrl',U='begin',T='bootstrap',R='clan',ab='clan.nocache.js',nb='clan::',kb='clear.cache.gif',qb='content',Cb='de',Db='default',Yb='en',Z='end',Qb='gecko',Rb='gecko1_8',V='gwt.codesvr=',W='gwt.hosted=',X='gwt.hybrid',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Ub='hosted.html?clan',Pb='ie6',Ob='ie8',xb='iframe',jb='img',yb="javascript:''",Tb='loadExternalRefs',Bb='locale',Eb='locale=',lb='meta',Ab='moduleRequested',Y='moduleStartup',Nb='msie',mb='name',Kb='opera',zb='position:absolute;width:0;height:0;border:none',Mb='safari',_='script',Vb='selectingPermutation',S='startup',Sb='unknown',Jb='user.agent',Lb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=Q,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:U});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(V)!=-1||(c.indexOf(W)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(X)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(R);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return I(a)}}clan=null;c.gwtOnLoad(z,R,t,y);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Z})}}
function D(){if(u[$]){t=u[$];return t}var e;var f=n.getElementsByTagName(_);for(var g=0;g<f.length;++g){if(f[g].src.indexOf(ab)!=-1){e=f[g]}}if(!e){var h=bb;var i;n.write(cb+h+db);i=n.getElementById(h);e=i&&i.previousSibling;while(e&&e.tagName!=eb){e=e.previousSibling}}function j(a){var b=a.lastIndexOf(fb);if(b==-1){b=a.length}var c=a.indexOf(gb);if(c==-1){c=a.length}var d=a.lastIndexOf(hb,Math.min(c,b));return d>=0?a.substring(0,d+1):Q}
;if(e&&e.src){t=j(e.src)}if(t==Q){var k=n.getElementsByTagName(ib);if(k.length>0){t=k[k.length-1].href}else{t=j(n.location.href)}}else if(t.match(/^\w+:\/\//)){}else{var l=n.createElement(jb);l.src=t+kb;t=j(l.src)}if(i){i.parentNode.removeChild(i)}return t}
function E(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,Q);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=Q}u[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{A=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function F(a,b){return b in v[a]}
function G(a){var b=u[a];return b==null?null:b}
function H(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function I(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var J;function K(){if(!J){J=true;var a=n.createElement(xb);a.src=yb;a.id=R;a.style.cssText=zb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Y,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(t+M)}}
w[Bb]=function(){try{var b;var c=Cb||Db;if(b==null){var d=location.search;var e=d.indexOf(Eb);if(e>=0){var f=d.substring(e);var g=f.indexOf(rb)+1;var h=f.indexOf(Fb);if(h==-1){h=f.length}b=f.substring(g,h)}}if(b==null){b=G(Bb)}if(b==null){b=m[Gb]}else{m[Gb]=b||c}if(b==null){return c}while(!F(Bb,b)){var i=b.lastIndexOf(Hb);if(i==-1){b=c;break}else{b=b.substring(0,i)}}return b}catch(a){alert(Ib+a);return Db}};v[Bb]={de:0,'default':1,en:2};w[Jb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Kb)!=-1){return Kb}else if(b.indexOf(Lb)!=-1){return Mb}else if(b.indexOf(Nb)!=-1){if(document.documentMode>=8){return Ob}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Pb}}}}else if(b.indexOf(Qb)!=-1){return Rb}return Sb};v[Jb]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};clan.onScriptLoad=function(){if(J){r=true;C()}};clan.onInjectionDone=function(){q=true;o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Tb,millis:(new Date).getTime(),type:Z});C()};E();D();var L;var M;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(R))){m.location.reload();return}M=Ub;L=Q}o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Vb});if(!B()){try{H([Cb,Rb],Wb);H([Db,Rb],Xb);H([Yb,Ob],Zb);H([Yb,Pb],$b);H([Cb,Kb],_b);H([Db,Ob],ac);H([Db,Pb],bc);H([Cb,Pb],cc);H([Yb,Rb],dc);H([Yb,Mb],ec);H([Db,Mb],fc);H([Db,Kb],gc);H([Cb,Ob],hc);H([Yb,Kb],ic);H([Cb,Mb],jc);L=x[I(Bb)][I(Jb)];var N=L.indexOf(kc);if(N!=-1){y=Number(L.substring(N+1));L=L.substring(0,N)}M=L+lc}catch(a){return}}var O;function P(){if(!s){s=true;C();if(n.removeEventListener){n.removeEventListener(mc,P,false)}if(O){clearInterval(O)}}}
if(n.addEventListener){n.addEventListener(mc,function(){K();P()},false)}var O=setInterval(function(){if(/loaded|complete/.test(n.readyState)){K();P()}},50);o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:T,millis:(new Date).getTime(),type:Z});o&&o({moduleName:R,sessionId:p,subSystem:S,evtGroup:Tb,millis:(new Date).getTime(),type:U});n.write(nc)}
clan();