/*
 * Shadowbox.js, version 3.0.3
 * http://shadowbox-js.com/
 *
 * Copyright 2007-2010, Michael J. I. Jackson
 * Date: 2011-01-13 23:38:19 +0000
 */
(function(s,oa){function S(b){if(a.options.enableKeys)(b?j:C)(document,"keydown",pa)}function pa(b){if(!(b.metaKey||b.shiftKey||b.altKey||b.ctrlKey)){var d;switch(b.which?b.which:b.keyCode){case 81:case 88:case 27:d=a.close;break;case 37:d=a.previous;break;case 39:d=a.next;break;case 32:d=typeof o=="number"?a.pause:a.play}if(d){b.preventDefault();d()}}}function $(b){S(false);var d=a.getCurrent(),c=d.player=="inline"?"html":d.player;if(typeof a[c]!="function")throw"unknown player "+c;if(b){a.player.remove();
a.revertOptions();a.applyOptions(d.options||{})}a.player=new a[c](d,a.playerId);if(a.gallery.length>1){d=a.gallery[a.current+1]||a.gallery[0];if(d.player=="img")(new Image).src=d.content;d=a.gallery[a.current-1]||a.gallery[a.gallery.length-1];if(d.player=="img")(new Image).src=d.content}a.skin.onLoad(b,qa)}function qa(){if(p)if(typeof a.player.ready!="undefined")var b=setInterval(function(){if(p){if(a.player.ready){clearInterval(b);b=null;a.skin.onReady(aa)}}else{clearInterval(b);b=null}},10);else a.skin.onReady(aa)}
function aa(){if(p){a.player.append(a.skin.body,a.dimensions);a.skin.onShow(ra)}}function ra(){if(p){a.player.onLoad&&a.player.onLoad();a.options.onFinish(a.getCurrent());a.isPaused()||a.play();S(true)}}function v(b,d){for(var c in d)b[c]=d[c];return b}function q(b,d){for(var c=0,e=b.length,f=b[0];c<e&&d.call(f,c,f)!==false;f=b[++c]);}function ba(b,d){return b.replace(/\{(\w+?)\}/g,function(c,e){return d[e]})}function J(){}function i(b){return document.getElementById(b)}function T(b){b.parentNode.removeChild(b)}
function ca(b){return[b.pageX||b.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),b.pageY||b.clientY+(document.documentElement.scrollTop||document.body.scrollTop)]}function j(b,d,c){if(b.addEventListener)b.addEventListener(d,c,false);else if(!(b.nodeType===3||b.nodeType===8)){if(b.setInterval&&b!==s&&!b.frameElement)b=s;if(!c.__guid)c.__guid=j.guid++;if(!b.events)b.events={};var e=b.events[d];if(!e){e=b.events[d]={};if(b["on"+d])e[0]=b["on"+d]}e[c.__guid]=c;b["on"+d]=j.handleEvent}}
function C(b,d,c){if(b.removeEventListener)b.removeEventListener(d,c,false);else b.events&&b.events[d]&&delete b.events[d][c.__guid]}function da(){if(!U){try{document.documentElement.doScroll("left")}catch(b){setTimeout(da,1);return}a.load()}}function ea(b){a.open(this);a.gallery.length&&b.preventDefault()}function fa(){var b=a.dimensions;v(w.style,{height:b.innerHeight+"px",width:b.innerWidth+"px"})}function ga(b){b.preventDefault();b=ca(b);n.startX=b[0];n.startY=b[1];A=i(a.player.id);j(document,
"mousemove",ha);j(document,"mouseup",ia);if(a.isGecko)w.style.cursor="-moz-grabbing"}function ha(b){var d=a.player,c=a.dimensions;b=ca(b);var e=b[0]-n.startX;n.startX+=e;n.x=Math.max(Math.min(0,n.x+e),c.innerWidth-d.width);b=b[1]-n.startY;n.startY+=b;n.y=Math.max(Math.min(0,n.y+b),c.innerHeight-d.height);v(A.style,{left:n.x+"px",top:n.y+"px"})}function ia(){C(document,"mousemove",ha);C(document,"mouseup",ia);if(a.isGecko)w.style.cursor="-moz-grab"}function r(b,d,c,e,f){var g=d=="opacity",h=g?a.setOpacity:
function(O,sa){O.style[d]=""+sa+"px"};if(e==0||!g&&!a.options.animate||g&&!a.options.animateFade){h(b,c);f&&f()}else{var l=parseFloat(a.getStyle(b,d))||0,D=c-l;if(D==0)f&&f();else{e*=1E3;var E=(new Date).getTime(),K=a.ease,L=E+e,F,H=setInterval(function(){F=(new Date).getTime();if(F>=L){clearInterval(H);H=null;h(b,c);f&&f()}else h(b,l+K((F-E)/e)*D)},10)}}}function ja(){t.style.height=a.getWindowSize("Height")+"px";t.style.width=a.getWindowSize("Width")+"px"}function V(){t.style.top=document.documentElement.scrollTop+
"px";t.style.left=document.documentElement.scrollLeft+"px"}function ka(b){if(b)q(W,function(d,c){c[0].style.visibility=c[1]||""});else{W=[];q(a.options.troubleElements,function(d,c){q(document.getElementsByTagName(c),function(e,f){W.push([f,f.style.visibility]);f.style.visibility="hidden"})})}}function x(b,d){var c=i("sb-nav-"+b);if(c)c.style.display=d?"":"none"}function la(b,d){var c=i("sb-loading"),e=a.getCurrent().player;e=e=="img"||e=="html";if(b){a.setOpacity(c,0);c.style.display="block";var f=
function(){a.clearOpacity(c);d&&d()};e?r(c,"opacity",1,a.options.fadeDuration,f):f()}else{f=function(){c.style.display="none";a.clearOpacity(c);d&&d()};e?r(c,"opacity",0,a.options.fadeDuration,f):f()}}function ta(b,d){var c=i("sb-title"),e=i("sb-info");c=c.offsetHeight;e=e.offsetHeight;var f=i("sb-title-inner"),g=i("sb-info-inner"),h=b?0.35:0;r(f,"marginTop",c,h);r(g,"marginTop",e*-1,h,function(){f.style.visibility=g.style.visibility="hidden";d()})}function M(b,d,c,e){var f=i("sb-wrapper-inner");
c=c?a.options.resizeDuration:0;r(B,"top",d,c);r(f,"height",b,c,e)}function N(b,d,c,e){c=c?a.options.resizeDuration:0;r(B,"left",d,c);r(B,"width",b,c,e)}function X(b,d){var c=i("sb-body-inner");b=parseInt(b);d=parseInt(d);var e=B.offsetHeight-c.offsetHeight;c=B.offsetWidth-c.offsetWidth;var f=y.offsetHeight,g=y.offsetWidth,h=parseInt(a.options.viewportPadding)||20;return a.setDimensions(b,d,f,g,e,c,h,a.player&&a.options.handleOversize!="drag")}var a={version:"3.0.3"},k=navigator.userAgent.toLowerCase();
if(k.indexOf("windows")>-1||k.indexOf("win32")>-1)a.isWindows=true;else if(k.indexOf("macintosh")>-1||k.indexOf("mac os x")>-1)a.isMac=true;else if(k.indexOf("linux")>-1)a.isLinux=true;a.isIE=k.indexOf("msie")>-1;a.isIE6=k.indexOf("msie 6")>-1;a.isIE7=k.indexOf("msie 7")>-1;a.isGecko=k.indexOf("gecko")>-1&&k.indexOf("safari")==-1;a.isWebKit=k.indexOf("applewebkit/")>-1;var ua=/#(.+)$/,va=/^(light|shadow)box\[(.*?)\]/i,wa=/\s*([a-z_]*?)\s*=\s*(.+)\s*/,xa=/[0-9a-z]+$/i,ya=/(.+\/)shadowbox\.js/i,p=false,
ma=false,na={},z=0,P,o;a.current=-1;a.dimensions=null;a.ease=function(b){return 1+Math.pow(b-1,3)};a.errorInfo={fla:{name:"Flash",url:"http://www.adobe.com/products/flashplayer/"},qt:{name:"QuickTime",url:"http://www.apple.com/quicktime/download/"},wmp:{name:"Windows Media Player",url:"http://www.microsoft.com/windows/windowsmedia/"},f4m:{name:"Flip4Mac",url:"http://www.flip4mac.com/wmv_download.htm"}};a.gallery=[];a.onReady=J;a.path=null;a.player=null;a.playerId="sb-player";a.options={animate:true,
animateFade:true,autoplayMovies:true,continuous:false,enableKeys:true,flashParams:{bgcolor:"#000000",allowfullscreen:true},flashVars:{},flashVersion:"9.0.115",handleOversize:"resize",handleUnsupported:"link",onChange:J,onClose:J,onFinish:J,onOpen:J,showMovieControls:true,skipSetup:false,slideshowDelay:0,viewportPadding:20};a.getCurrent=function(){return a.current>-1?a.gallery[a.current]:null};a.hasNext=function(){return a.gallery.length>1&&(a.current!=a.gallery.length-1||a.options.continuous)};a.isOpen=
function(){return p};a.isPaused=function(){return o=="pause"};a.applyOptions=function(b){na=v({},a.options);v(a.options,b)};a.revertOptions=function(){v(a.options,na)};a.init=function(b,d){if(!ma){ma=true;a.skin.options&&v(a.options,a.skin.options);b&&v(a.options,b);if(!a.path)for(var c,e=document.getElementsByTagName("script"),f=0,g=e.length;f<g;++f)if(c=ya.exec(e[f].src)){a.path=c[1];break}if(d)a.onReady=d;if(document.readyState==="complete")a.load();else if(document.addEventListener){document.addEventListener("DOMContentLoaded",
I,false);s.addEventListener("load",a.load,false)}else if(document.attachEvent){document.attachEvent("onreadystatechange",I);s.attachEvent("onload",a.load);c=false;try{c=s.frameElement===null}catch(h){}document.documentElement.doScroll&&c&&da()}}};a.open=function(b){if(!p){b=a.makeGallery(b);a.gallery=b[0];a.current=b[1];b=a.getCurrent();if(b!=null){a.applyOptions(b.options||{});b=a.errorInfo;for(var d=a.plugins,c,e,f,g,h=0;h<a.gallery.length;++h){c=a.gallery[h];e=false;f=null;switch(c.player){case "flv":case "swf":d.fla||
(f="fla");break;case "qt":d.qt||(f="qt");break;case "wmp":if(a.isMac)if(d.qt&&d.f4m)c.player="qt";else f="qtf4m";else d.wmp||(f="wmp");break;case "qtwmp":if(d.qt)c.player="qt";else if(d.wmp)c.player="wmp";else f="qtwmp"}if(f)if(a.options.handleUnsupported=="link"){switch(f){case "qtf4m":g="shared";f=[b.qt.url,b.qt.name,b.f4m.url,b.f4m.name];break;case "qtwmp":g="either";f=[b.qt.url,b.qt.name,b.wmp.url,b.wmp.name];break;default:g="single";f=[b[f].url,b[f].name]}c.player="html";c.content='<div class="sb-message">'+
ba(a.lang.errors[g],f)+"</div>"}else e=true;else if(c.player=="inline")if(g=ua.exec(c.content))if(g=i(g[1]))c.content=g.innerHTML;else e=true;else e=true;else if(c.player=="swf"||c.player=="flv"){g=c.options&&c.options.flashVersion||a.options.flashVersion;if(a.flash&&!a.flash.hasFlashPlayerVersion(g)){c.width=310;c.height=177}}if(e){a.gallery.splice(h,1);if(h<a.current)--a.current;else if(h==a.current)a.current=h>0?h-1:h;--h}}if(a.gallery.length){b=a.getCurrent();if(a.options.onOpen(b)!==false){p=
true;a.skin.onOpen(b,$)}}}}};a.close=function(){if(p){p=false;if(a.player){a.player.remove();a.player=null}if(typeof o=="number"){clearTimeout(o);o=null}z=0;S(false);a.options.onClose(a.getCurrent());a.skin.onClose();a.revertOptions()}};a.play=function(){if(a.hasNext()){z||(z=a.options.slideshowDelay*1E3);if(z){P=(new Date).getTime();o=setTimeout(function(){z=P=0;a.next()},z);a.skin.onPlay&&a.skin.onPlay()}}};a.pause=function(){if(typeof o=="number")if(z=Math.max(0,z-((new Date).getTime()-P))){clearTimeout(o);
o="pause";a.skin.onPause&&a.skin.onPause()}};a.change=function(b){if(!(b in a.gallery))if(a.options.continuous){b=b<0?a.gallery.length+b:0;if(!(b in a.gallery))return}else return;a.current=b;if(typeof o=="number"){clearTimeout(o);o=null;z=P=0}a.options.onChange(a.getCurrent());$(true)};a.next=function(){a.change(a.current+1)};a.previous=function(){a.change(a.current-1)};a.setDimensions=function(b,d,c,e,f,g,h,l){var D=b,E=d,K=2*h+f;if(b+K>c)b=c-K;var L=2*h+g;if(d+L>e)d=e-L;var F=(D-b)/D,H=(E-d)/E,
O=F>0||H>0;if(l&&O)if(F>H)d=Math.round(E/D*b);else if(H>F)b=Math.round(D/E*d);a.dimensions={height:b+f,width:d+g,innerHeight:b,innerWidth:d,top:Math.floor((c-(b+K))/2+h),left:Math.floor((e-(d+L))/2+h),oversized:O};return a.dimensions};a.makeGallery=function(b){var d=[],c=-1;if(typeof b=="string")b=[b];if(typeof b.length=="number"){q(b,function(g,h){d[g]=h.content?h:{content:h}});c=0}else{if(b.tagName){var e=a.getCache(b);b=e?e:a.makeObject(b)}if(b.gallery){d=[];for(var f in a.cache){e=a.cache[f];
if(e.gallery&&e.gallery==b.gallery){if(c==-1&&e.content==b.content)c=d.length;d.push(e)}}if(c==-1){d.unshift(b);c=0}}else{d=[b];c=0}}q(d,function(g,h){d[g]=v({},h)});return[d,c]};a.makeObject=function(b,d){var c={content:b.href,title:b.getAttribute("title")||"",link:b};if(d){d=v({},d);q(["player","title","height","width","gallery"],function(g,h){if(typeof d[h]!="undefined"){c[h]=d[h];delete d[h]}});c.options=d}else c.options={};if(!c.player)c.player=a.getPlayer(c.content);var e=b.getAttribute("rel");
if(e){var f=e.match(va);if(f)c.gallery=escape(f[2]);q(e.split(";"),function(g,h){if(f=h.match(wa))c[f[1]]=f[2]})}return c};a.getPlayer=function(b){if(b.indexOf("data:image")>-1)return"img";if(b.indexOf("#")>-1&&b.indexOf(document.location.href)==0)return"inline";var d=b.indexOf("?");if(d>-1)b=b.substring(0,d);var c;if(b=b.match(xa))c=b[0].toLowerCase();if(c){if(a.img&&a.img.ext.indexOf(c)>-1)return"img";if(a.swf&&a.swf.ext.indexOf(c)>-1)return"swf";if(a.flv&&a.flv.ext.indexOf(c)>-1)return"flv";if(a.qt&&
a.qt.ext.indexOf(c)>-1)return a.wmp&&a.wmp.ext.indexOf(c)>-1?"qtwmp":"qt";if(a.wmp&&a.wmp.ext.indexOf(c)>-1)return"wmp"}return"iframe"};if(!Array.prototype.indexOf)Array.prototype.indexOf=function(b,d){var c=this.length>>>0;d=d||0;if(d<0)d+=c;for(;d<c;++d)if(d in this&&this[d]===b)return d;return-1};var Q=true,R=true;a.getStyle=function(){var b=/opacity=([^)]*)/,d=document.defaultView&&document.defaultView.getComputedStyle;return function(c,e){var f;if(!Q&&e=="opacity"&&c.currentStyle){f=b.test(c.currentStyle.filter||
"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(d){var g=d(c,null);if(g)f=g[e];if(e=="opacity"&&f=="")f="1"}else f=c.currentStyle[e];return f}}();a.appendHTML=function(b,d){if(b.insertAdjacentHTML)b.insertAdjacentHTML("BeforeEnd",d);else if(b.lastChild){var c=b.ownerDocument.createRange();c.setStartAfter(b.lastChild);c=c.createContextualFragment(d);b.appendChild(c)}else b.innerHTML=d};a.getWindowSize=function(b){if(document.compatMode==="CSS1Compat")return document.documentElement["client"+
b];return document.body["client"+b]};a.setOpacity=function(b,d){var c=b.style;if(Q)c.opacity=d==1?"":d;else{c.zoom=1;if(d==1){if(typeof c.filter=="string"&&/alpha/i.test(c.filter))c.filter=c.filter.replace(/\s*[\w\.]*alpha\([^\)]*\);?/gi,"")}else c.filter=(c.filter||"").replace(/\s*[\w\.]*alpha\([^\)]*\)/gi,"")+" alpha(opacity="+d*100+")"}};a.clearOpacity=function(b){a.setOpacity(b,1)};j.guid=1;j.handleEvent=function(b){var d=true;b=b||j.fixEvent(((this.ownerDocument||this.document||this).parentWindow||
s).event);var c=this.events[b.type],e;for(e in c){this.__handleEvent=c[e];if(this.__handleEvent(b)===false)d=false}return d};j.preventDefault=function(){this.returnValue=false};j.stopPropagation=function(){this.cancelBubble=true};j.fixEvent=function(b){b.preventDefault=j.preventDefault;b.stopPropagation=j.stopPropagation;return b};var U=false,I;if(document.addEventListener)I=function(){document.removeEventListener("DOMContentLoaded",I,false);a.load()};else if(document.attachEvent)I=function(){if(document.readyState===
"complete"){document.detachEvent("onreadystatechange",I);a.load()}};a.load=function(){if(!U){if(!document.body)return setTimeout(a.load,13);U=true;var b=document.body,d=document.createElement("div");Q=typeof d.style.opacity==="string";d.style.position="fixed";d.style.margin=0;d.style.top="20px";b.appendChild(d,b.firstChild);R=d.offsetTop==20;b.removeChild(d);a.onReady();a.options.skipSetup||a.setup();a.skin.init()}};a.plugins={};if(navigator.plugins&&navigator.plugins.length){var G=[];q(navigator.plugins,
function(b,d){G.push(d.name)});G=G.join(",");k=G.indexOf("Flip4Mac")>-1;a.plugins={fla:G.indexOf("Shockwave Flash")>-1,qt:G.indexOf("QuickTime")>-1,wmp:!k&&G.indexOf("Windows Media")>-1,f4m:k}}else{k=function(b){var d;try{d=new ActiveXObject(b)}catch(c){}return!!d};a.plugins={fla:k("ShockwaveFlash.ShockwaveFlash"),qt:k("QuickTime.QuickTime"),wmp:k("wmplayer.ocx"),f4m:false}}var za=/^(light|shadow)box/i,Aa=1;a.cache={};a.select=function(b){var d=[];if(b){var c=b.length;if(c)if(typeof b=="string"){if(a.find)d=
a.find(b)}else if(c==2&&typeof b[0]=="string"&&b[1].nodeType){if(a.find)d=a.find(b[0],b[1])}else for(var e=0;e<c;++e)d[e]=b[e];else d.push(b)}else{var f;q(document.getElementsByTagName("a"),function(g,h){(f=h.getAttribute("rel"))&&za.test(f)&&d.push(h)})}return d};a.setup=function(b,d){q(a.select(b),function(c,e){a.addCache(e,d)})};a.teardown=function(b){q(a.select(b),function(d,c){a.removeCache(c)})};a.addCache=function(b,d){var c=b.shadowboxCacheKey;if(c==oa){c=Aa++;b.shadowboxCacheKey=c;j(b,"click",
ea)}a.cache[c]=a.makeObject(b,d)};a.removeCache=function(b){C(b,"click",ea);delete a.cache[b.shadowboxCacheKey];b.shadowboxCacheKey=null};a.getCache=function(b){b=b.shadowboxCacheKey;return b in a.cache&&a.cache[b]};a.clearCache=function(){for(var b in a.cache)a.removeCache(a.cache[b].link);a.cache={}};a.lang={code:"en",of:"of",loading:"loading",cancel:"Cancel",next:"Next",previous:"Previous",play:"Play",pause:"Pause",close:"Close",errors:{single:'You must install the <a href="{0}">{1}</a> browser plugin to view this content.',
shared:'You must install both the <a href="{0}">{1}</a> and <a href="{2}">{3}</a> browser plugins to view this content.',either:'You must install either the <a href="{0}">{1}</a> or the <a href="{2}">{3}</a> browser plugin to view this content.'}};var u,n,w,A;a.img=function(b,d){this.obj=b;this.id=d;this.ready=false;var c=this;u=new Image;u.onload=function(){c.height=b.height?parseInt(b.height,10):u.height;c.width=b.width?parseInt(b.width,10):u.width;c.ready=true;u=u.onload=null};u.src=b.content};
a.img.ext=["bmp","gif","jpg","jpeg","png"];a.img.prototype={append:function(b,d){var c=document.createElement("img");c.id=this.id;c.src=this.obj.content;c.style.position="absolute";var e,f;if(d.oversized&&a.options.handleOversize=="resize"){e=d.innerHeight;f=d.innerWidth}else{e=this.height;f=this.width}c.setAttribute("height",e);c.setAttribute("width",f);b.appendChild(c)},remove:function(){var b=i(this.id);b&&T(b);if(w){C(w,"mousedown",ga);T(w);w=null}A=null;if(u)u=u.onload=null},onLoad:function(){if(a.dimensions.oversized&&
a.options.handleOversize=="drag"){n={x:0,y:0,startX:null,startY:null};var b=["position:absolute","cursor:"+(a.isGecko?"-moz-grab":"move"),"background-color:"+(a.isIE?"#fff;filter:alpha(opacity=0)":"transparent")].join(";");a.appendHTML(a.skin.body,'<div id="sb-drag-proxy" style="'+b+'"></div>');w=i("sb-drag-proxy");fa();j(w,"mousedown",ga)}},onWindowResize:function(){var b=a.dimensions;switch(a.options.handleOversize){case "resize":var d=i(this.id);d.height=b.innerHeight;d.width=b.innerWidth;break;
case "drag":if(A){d=parseInt(a.getStyle(A,"top"));var c=parseInt(a.getStyle(A,"left"));if(d+this.height<b.innerHeight)A.style.top=b.innerHeight-this.height+"px";if(c+this.width<b.innerWidth)A.style.left=b.innerWidth-this.width+"px";fa()}}}};var Y=false,W=[],Ba=["sb-nav-close","sb-nav-next","sb-nav-play","sb-nav-pause","sb-nav-previous"],t,y,B,Z=true,m={};m.markup='<div id="sb-container"><div id="sb-overlay"></div><div id="sb-wrapper"><div id="sb-title"><div id="sb-title-inner"></div></div><div id="sb-wrapper-inner"><div id="sb-body"><div id="sb-body-inner"></div><div id="sb-loading"><div id="sb-loading-inner"><span>{loading}</span></div></div></div></div><div id="sb-info"><div id="sb-info-inner"><div id="sb-counter"></div><div id="sb-nav"><a id="sb-nav-close" title="{close}" onclick="Shadowbox.close()"></a><a id="sb-nav-next" title="{next}" onclick="Shadowbox.next()"></a><a id="sb-nav-play" title="{play}" onclick="Shadowbox.play()"></a><a id="sb-nav-pause" title="{pause}" onclick="Shadowbox.pause()"></a><a id="sb-nav-previous" title="{previous}" onclick="Shadowbox.previous()"></a></div></div></div></div></div>';
m.options={animSequence:"sync",counterLimit:10,counterType:"default",displayCounter:true,displayNav:true,fadeDuration:0.35,initialHeight:160,initialWidth:320,modal:false,overlayColor:"#000",overlayOpacity:0.5,resizeDuration:0.35,showOverlay:true,troubleElements:["select","object","embed","canvas"]};m.init=function(){a.appendHTML(document.body,ba(m.markup,a.lang));m.body=i("sb-body-inner");t=i("sb-container");y=i("sb-overlay");B=i("sb-wrapper");if(!R)t.style.position="absolute";if(!Q){var b,d,c=/url\("(.*\.png)"\)/;
q(Ba,function(f,g){if(b=i(g))if(d=a.getStyle(b,"backgroundImage").match(c)){b.style.backgroundImage="none";b.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true,src="+d[1]+",sizingMethod=scale);"}})}var e;j(s,"resize",function(){if(e){clearTimeout(e);e=null}if(p)e=setTimeout(m.onWindowResize,10)})};m.onOpen=function(b,d){Z=false;t.style.display="block";ja();var c=X(a.options.initialHeight,a.options.initialWidth);M(c.innerHeight,c.top);N(c.width,c.left);if(a.options.showOverlay){y.style.backgroundColor=
a.options.overlayColor;a.setOpacity(y,0);a.options.modal||j(y,"click",a.close);Y=true}if(!R){V();j(s,"scroll",V)}ka();t.style.visibility="visible";Y?r(y,"opacity",a.options.overlayOpacity,a.options.fadeDuration,d):d()};m.onLoad=function(b,d){for(la(true);m.body.firstChild;)T(m.body.firstChild);ta(b,function(){if(p){if(!b)B.style.visibility="visible";var c=a.getCurrent();i("sb-title-inner").innerHTML=c.title||"";var e,f,g,h,l;if(a.options.displayNav){e=true;c=a.gallery.length;if(c>1)if(a.options.continuous)f=
l=true;else{f=c-1>a.current;l=a.current>0}if(a.options.slideshowDelay>0&&a.hasNext()){h=!a.isPaused();g=!h}}else e=f=g=h=l=false;x("close",e);x("next",f);x("play",g);x("pause",h);x("previous",l);f="";if(a.options.displayCounter&&a.gallery.length>1){c=a.gallery.length;if(a.options.counterType=="skip"){g=0;l=c;h=parseInt(a.options.counterLimit)||0;if(h<c&&h>2){l=Math.floor(h/2);g=a.current-l;if(g<0)g+=c;l=a.current+(h-l);if(l>c)l-=c}for(;g!=l;){if(g==c)g=0;f+='<a onclick="Shadowbox.change('+g+');"';
if(g==a.current)f+=' class="sb-counter-current"';f+=">"+ ++g+"</a>"}}else f=[a.current+1,a.lang.of,c].join(" ")}i("sb-counter").innerHTML=f;d()}})};m.onReady=function(b){if(p){var d=a.player,c=X(d.height,d.width),e=function(){var f=i("sb-title-inner"),g=i("sb-info-inner");f.style.visibility=g.style.visibility="";f.innerHTML!=""&&r(f,"marginTop",0,0.35);r(g,"marginTop",0,0.35,b)};switch(a.options.animSequence){case "hw":M(c.innerHeight,c.top,true,function(){N(c.width,c.left,true,e)});break;case "wh":N(c.width,
c.left,true,function(){M(c.innerHeight,c.top,true,e)});break;default:N(c.width,c.left,true);M(c.innerHeight,c.top,true,e)}}};m.onShow=function(b){la(false,b);Z=true};m.onClose=function(){R||C(s,"scroll",V);C(y,"click",a.close);B.style.visibility="hidden";var b=function(){t.style.visibility="hidden";t.style.display="none";ka(true)};Y?r(y,"opacity",0,a.options.fadeDuration,b):b()};m.onPlay=function(){x("play",false);x("pause",true)};m.onPause=function(){x("pause",false);x("play",true)};m.onWindowResize=
function(){if(Z){ja();var b=a.player,d=X(b.height,b.width);N(d.width,d.left);M(d.innerHeight,d.top);b.onWindowResize&&b.onWindowResize()}};a.skin=m;s.Shadowbox=a})(window);