<div id="loading-mask"></div>

<div id="header" class="x-hidden">
    <a href="http://www.dkfz.de/" target="_blank"><img style="float:right;" src="images/dkfzlogo.gif" /></a>
    <h1 class="header">Antibodydb</h1>
</div>

<!-- Fields required for history management -->
<form id="history-form" class="x-hidden">
    <input type="hidden" id="x-history-field" />
    <iframe id="x-history-frame"></iframe>
</form>
