# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/merb-extjs-direct.rb'

Hoe.new('merb-extjs-direct', Merb::ExtJS::Direct::VERSION) do |p|
  p.rubyforge_name = 'merb-extjs' # if different than lowercase project name
  p.developer('christocracy', 'chris.scott@extjs.com')
end

# vim: syntax=Ruby
